import Head from "next/head";
import CardHome from "../components/Card";
import Dashboard from "../components/Dashboard";
import EventoForm from "../components/Form";
import { View, X } from "lucide-react";
import Viewimg from "../components/Viewimg";
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
  AlertDialogTrigger,
} from "../components/reusable/alert";
import { useState } from "react";
import { Button } from "../components/reusable/button";
import EventDetails from "../components/Infoevents";
import { Card } from "../components/reusable/card";
import { Form } from "react-hook-form";

function YourComponent() {
  const [isOpen, setIsOpen] = useState(false);

  const openDialog = () => {
    setIsOpen(true);
  };

  const closeDialog = () => {
    setIsOpen(false);
  };

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <CardHome />
      </main>
    </>
  );
}

export default YourComponent;
