import Head from "next/head";
import { useEffect, useState } from "react";
import Dashboard from "../components/Dashboard";
import CardHome, { CardHomeProps } from "../components/Card";
import { Input } from "../components/reusable/input";

export default function Home() {
  const [cards, setCards] = useState([]);
  const [searchText, setSearchText] = useState("");
  const [filteredCards, setFilteredCards] = useState([]);

  useEffect(() => {
    fetch("/api/get-events")
      .then((response) => response.json())
      .then((data) => {
        setCards(data);
        console.log("Sucesso:", data);
      })
      .catch((error) => {
        console.error("Erro:", error);
      });
  }, []);

  const filterCards = () => {
    const filtered = cards.filter((card: CardHomeProps) =>
      card.nm_event.toLowerCase().includes(searchText.toLowerCase()),
    );
    setFilteredCards(filtered);
  };

  useEffect(() => {
    filterCards();
  }, [searchText, cards]);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Dashboard
          searchInput={
            <Input
              placeholder="Pesquisar..."
              value={searchText}
              onChange={(e) => setSearchText(e.target.value)}
            />
          }
        >
          {filteredCards.map((card: CardHomeProps) => (
            <CardHome key={card.nm_event} {...card} />
          ))}
        </Dashboard>
      </main>
    </>
  );
}
