import Head from "next/head";
import Link from "next/link";
import { Button } from "../components/reusable/button";
import { ThemeSwitcher } from "../components/theme-switcher";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-screen w-full bg-background flex justify-center items-center ">
        <ThemeSwitcher />
      </main>
    </>
  );
}
