import Head from "next/head";
import EventoForm from "../components/Form";
import { useEffect } from "react";
import { Card } from "../components/reusable/card";


function YourComponent() {
useEffect(() => {
    console.log("teste")
}, [])

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <EventoForm />
      </main>
    </>
  );
}

export default YourComponent;
